/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 0030481521022
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuExemplos = new javax.swing.JMenu();
        jMenuItemRetangulo = new javax.swing.JMenuItem();
        jMenuItemAluno = new javax.swing.JMenuItem();
        jMenuItemVendas = new javax.swing.JMenuItem();
        jMenuExercicios = new javax.swing.JMenu();
        jMenuItemExercicio1 = new javax.swing.JMenuItem();
        jMenuItemExercicio2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo Gui Menu");

        jMenuExemplos.setText("Exemplos");

        jMenuItemRetangulo.setText("Retangulo");
        jMenuItemRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRetanguloActionPerformed(evt);
            }
        });
        jMenuExemplos.add(jMenuItemRetangulo);

        jMenuItemAluno.setText("Aluno");
        jMenuItemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlunoActionPerformed(evt);
            }
        });
        jMenuExemplos.add(jMenuItemAluno);

        jMenuItemVendas.setText("Vendas");
        jMenuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendasActionPerformed(evt);
            }
        });
        jMenuExemplos.add(jMenuItemVendas);

        jMenuBar1.add(jMenuExemplos);

        jMenuExercicios.setText("Exercícios");

        jMenuItemExercicio1.setText("Exercício 1");
        jMenuItemExercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExercicio1ActionPerformed(evt);
            }
        });
        jMenuExercicios.add(jMenuItemExercicio1);

        jMenuItemExercicio2.setText("Exercício 2");
        jMenuItemExercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExercicio2ActionPerformed(evt);
            }
        });
        jMenuExercicios.add(jMenuItemExercicio2);

        jMenuBar1.add(jMenuExercicios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRetanguloActionPerformed
        new GuiRetangulo().setVisible(true);
    }//GEN-LAST:event_jMenuItemRetanguloActionPerformed

    private void jMenuItemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlunoActionPerformed
        new GuiAluno().setVisible(true);
    }//GEN-LAST:event_jMenuItemAlunoActionPerformed

    private void jMenuItemExercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExercicio1ActionPerformed
        new Exercicio1().setVisible(true);
    }//GEN-LAST:event_jMenuItemExercicio1ActionPerformed

    private void jMenuItemExercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExercicio2ActionPerformed
        new Exercicio2().setVisible(true);
    }//GEN-LAST:event_jMenuItemExercicio2ActionPerformed

    private void jMenuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendasActionPerformed
        new GuiVenda().setVisible(true);
    }//GEN-LAST:event_jMenuItemVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExemplos;
    private javax.swing.JMenu jMenuExercicios;
    private javax.swing.JMenuItem jMenuItemAluno;
    private javax.swing.JMenuItem jMenuItemExercicio1;
    private javax.swing.JMenuItem jMenuItemExercicio2;
    private javax.swing.JMenuItem jMenuItemRetangulo;
    private javax.swing.JMenuItem jMenuItemVendas;
    // End of variables declaration//GEN-END:variables
}
